USE MASTER
GO
IF EXISTS(SELECT * FROM SYS.DATABASES WHERE NAME='QL_DIEMRL')
BEGIN
        DROP DATABASE QL_DIEMRL
END
CREATE DATABASE QL_DIEMRL
GO
USE QL_DIEMRL
GO

Create table LOP (
ID_LOP int IDENTITY Primary key,
CODE_LOP nchar(255),
TEN_LOP nvarchar(255),
TRANGTHAI int DEFAULT '0',
ID_KHOA int,
KHOA int,
disabled int DEFAULT '0',
)
INSERT INTO LOP(CODE_LOP,TEN_LOP,ID_KHOA) values ('10DHTH3',N'Lớp 10DHTH3',1);
INSERT INTO LOP(CODE_LOP,TEN_LOP,ID_KHOA) values ('10DHTH4',N'Lớp 10DHTH4',1);
Create table HOC_KI (
ID_HK int IDENTITY Primary key,
CODE_HK nchar(255),
TEN_HK nvarchar(255),
TRANGTHAI int DEFAULT '0',
disabled int DEFAULT '0',
)
   INSERT INTO HOC_KI(CODE_HK,TEN_HK,TRANGTHAI) values ('HK2(2021-2022)','HK2(2021-2022)',1);
   INSERT INTO HOC_KI(CODE_HK,TEN_HK) values ('HK1(2022-2023)','HK1(2022-2023)');
   INSERT INTO HOC_KI(CODE_HK,TEN_HK) values ('HK2(2022-2023)','HK2(2022-2023)');

Create table NOI_QUY (
ID_NOI_QUY int IDENTITY Primary key,
CODE_NOI_QUY nchar(255),
TEN_NOI_QUY nvarchar(255),
DIEM INT,
disabled int DEFAULT '0',
)

Create table VAI_TRO (
ID_VAI_TRO int IDENTITY Primary key,
CODE_VAI_TRO nchar(255),
TEN_VAI_TRO nvarchar(255),
disabled int DEFAULT '0',
)

Create table LOAI_QUYEN (
ID_LOAI_QUYEN int IDENTITY Primary key,
CODE_LOAI_QUYEN nchar(255),
TEN_LOAI_QUYEN nvarchar(255),
disabled int DEFAULT '0',
)

Create table KHOA(
ID_KHOA int IDENTITY Primary key,
MA_KHOA nchar(10),
TEN_KHOA NVARCHAR(500),
disabled int DEFAULT '0',
)

Create table GIANG_VIEN(
ID_GV int IDENTITY Primary key,
MAGV nvarchar(10) ,
TENGV nvarchar(255),
DC ntext,
EMAIL nvarchar(255),
SDT nvarchar(255),
NGAYSINH date,
disabled int DEFAULT '0',
MATKHAU nvarchar(255),
ID_KHOA int,
ID_VAI_TRO int,
CONSTRAINT fk_CN_QUYEN FOREIGN KEY (ID_VAI_TRO) REFERENCES VAI_TRO(ID_VAI_TRO),
CONSTRAINT fk_CN_NHANVIEN FOREIGN KEY (ID_KHOA) REFERENCES KHOA(ID_KHOA),
) 


Create table LOAIQUYENOFGV(
ID_GV int,
ID_LOAI_QUYEN int,
disabled int DEFAULT '0',
CONSTRAINT pk_LOAIQUYENOFNHANVIEN PRIMARY KEY(ID_GV,ID_LOAI_QUYEN),

)

Create table LOAIQUYENOFVAITRO (
ID_VAI_TRO int,
ID_LOAI_QUYEN int,
disabled int DEFAULT '0',
CONSTRAINT pk_LOAIQUYENOFQUYEN PRIMARY KEY(ID_VAI_TRO,ID_LOAI_QUYEN),
)

CREATE TABLE HOATDONG(
IDHD INT IDENTITY Primary key,
MAHD NVARCHAR(10),
TIEUDE ntext,
NOIDUNG ntext,
NGUOITAO int,
NGAYTAO DATE,
NGUOISUA int,
NGAYSUA DATE,
NGUOIDUYET int,
NGAYDUYET NVARCHAR(10),
TRANGTHAI int DEFAULT '0',
NGAYBATDAUDK DATE,
NGAYKETTHUCDK DATE,
GHICHU ntext,
DIEMRL INT DEFAULT 1,
LOAI INT,
TINHTRANG INT DEFAULT '0',
SONGUOI INT DEFAULT 1,
HINHANH ntext,
ID_HK int,
ID_KHOA int,
)

ALTER TABLE HOATDONG
ADD DIADIEM ntext;

CREATE TABLE HOATDONGTHEONGAY(
IDBUOI INT IDENTITY Primary key,
IDHD INT,
LOAI_BUOI INT,
NGAYBATDAUDIEMDANH DATE,
NGAYKETTHUCDIENDANH DATE,
disabled int DEFAULT '0',
)
ALTER TABLE HOATDONGTHEONGAY
ADD TRANGTHAI int DEFAULT '0';

CREATE TABLE SINHVIEN(
ID_SV int IDENTITY Primary key,
MASV NCHAR(10),
TENSV NVARCHAR(500),
NGAYSINH DATE,
DIACHI NTEXT,
SDT NVARCHAR(10),
EMAIL NVARCHAR(500),
MATKHAU NVARCHAR(100),
ID_KHOA int,
disabled int DEFAULT '0',
)

ALTER TABLE SINHVIEN
ADD BACDAOTAO int DEFAULT '0';

ALTER TABLE SINHVIEN
ADD NOISINH NTEXT;

ALTER TABLE SINHVIEN
ADD GIOITINH INT;

ALTER TABLE SINHVIEN
ADD IDLOP INT;

ALTER TABLE SINHVIEN
ADD HINHANH NTEXT;

CREATE TABLE DANGKY (
IDDK INT IDENTITY Primary key,
IDSV int,
MASV NCHAR(10),
SDT NVARCHAR(10),
EMAIL NVARCHAR(100),
GHICHU TEXT,
NGAYDANGKY DATETIME,
TRANGTHAI INT DEFAULT 0,
IDBUOI INT
)

ALTER TABLE DANGKY
ADD NGAYHUY DATETIME;

CREATE TABLE DIEMDANH (
IDDD INT IDENTITY Primary key,
IDSV int,
MASV NVARCHAR(10),
SDT NVARCHAR(10),
EMAIL NVARCHAR(100),
GHICHU TEXT,
NGAYDIEMDANH DATETIME,
TRANGTHAI INT DEFAULT 0,
IDBUOI INT
)

CREATE TABLE PHAN_HOI(
ID_PHAN_HOI INT IDENTITY Primary key,
MA_PHAN_HOI NVARCHAR(10),
IDSV  INT,
TIEUDE nTEXT,
NOIDUNG nTEXT,
TRANGTHAI INT DEFAULT 0,
TEP nTEXT,
LOAI_PHAN_HOI INT,
IDBUOI INT DEFAULT NULL,
ID_VI_PHAM INT DEFAULT NULL,
NGAYTAO DATETIME,
NGAYDUYET DATETIME,
NGUOIDUYET INT,
IDHK int,
)



Select * from PHAN_HOI

CREATE TABLE VI_PHAM(
ID_VI_PHAM INT IDENTITY Primary key,
MA_VI_PHAM NVARCHAR(10),
TIEUDE ntext,
NOIDUNG ntext,
NGUOITAO int,
NGAYTAO DATE,
NGUOISUA int,
NGAYSUA DATE,
NGUOIDUYET int,
NGAYDUYET NVARCHAR(10),
TRANGTHAI int DEFAULT '0',
ID_NOI_QUY int,
IDSV int,
IDHK int,
)

CREATE TABLE KETQUA (
ID_KQ INT IDENTITY Primary key,
IDSV INT,
IDHK INT,
DIEM INT,
LOAI NVARCHAR(3),
)


Select LOAIQUYENOFVAITRO.ID_LOAI_QUYEN,LOAI_QUYEN.MA_LOAI_QUYEN,LOAI_QUYEN.TEN_LOAI_QUYEN 
from LOAI_QUYEN,VAI_TRO,LOAIQUYENOFVAITRO 
where LOAIQUYENOFVAITRO.ID_LOAI_QUYEN=LOAI_QUYEN.ID_LOAI_QUYEN and VAI_TRO.ID_VAI_TRO = LOAIQUYENOFVAITRO.ID_VAI_TRO and LOAIQUYENOFVAITRO.disabled = 0 and LOAIQUYENOFVAITRO.ID_LOAI_QUYEN = '" + ma + "'

select LOAI_QUYEN.ID_LOAI_QUYEN,CODE_LOAI_QUYEN,TEN_LOAI_QUYEN from LOAIQUYENOFGV,GIANG_VIEN,LOAI_QUYEN 
where LOAIQUYENOFGV.MAGV =  GIANG_VIEN.MAGV and LOAI_QUYEN.ID_LOAI_QUYEN = LOAIQUYENOFGV.ID_LOAI_QUYEN and GIANG_VIEN.ID_VAI_TRO = '1' and GIANG_VIEN.MAGV='1' and LOAIQUYENOFGV.disabled = 0 
and LOAI_QUYEN.ID_LOAI_QUYEN IN (select ID_LOAI_QUYEN from LOAIQUYENOFVAITRO where ID_VAI_TRO='1' and disabled = 0)

select HOATDONG.*,ngtao.TENGV,ngsua.TENGV,ngduyet.TENGV,KHOA.TEN_KHOA,HOC_KI.TEN_HK from HOATDONG LEFT JOIN GIANG_VIEN as ngtao ON ngtao.ID_GV = HOATDONG.NGUOITAO
LEFT JOIN GIANG_VIEN as ngsua ON ngsua.ID_GV = HOATDONG.NGUOITAO
LEFT JOIN GIANG_VIEN as ngduyet ON ngduyet.ID_GV = HOATDONG.NGUOITAO
LEFT JOIN KHOA ON KHOA.ID_KHOA = HOATDONG.ID_KHOA
LEFT JOIN HOC_KI ON HOC_KI.ID_HK = HOATDONG.ID_HK

select NGAYBATDAUDIEMDANH from HOATDONGTHEONGAY where IDHD='4' and disabled = 0

select * from SINHVIEN


update HOATDONGTHEONGAY set trangThai = 0


select top 2 HOATDONG.* from HOATDONG where trangthai = 1 and NGAYDUYET IS NOT NULL order by NGAYDUYET desc

select * from HOATDONG 
INNER JOIN HOATDONGTHEONGAY ON HOATDONG.IDHD = HOATDONGTHEONGAY.IDHD
INNER JOIN DANGKY ON DANGKY.IDBUOI = HOATDONGTHEONGAY.IDBUOI
WHERE DANGKY.IDSV = 1 AND HOATDONG.ID_HK = 1 AND DANGKY.TRANGTHAI = 0 AND HOATDONGTHEONGAY.TRANGTHAI  != 1 



update HOATDONGTHEONGAY
set TRANGTHAI = 4
from HOATDONG
where disabled = 0 and HOATDONG.IDHD = HOATDONGTHEONGAY.IDHD and NGAYKETTHUCDK < GETDATE()

select *  from HOATDONGTHEONGAY
where  TRANGTHAI != 1 and TRANGTHAI in (2,4) and NGAYBATDAUDIEMDANH < GETDATE()


update HOATDONGTHEONGAY set TRANGTHAI = 4 from HOATDONG where disabled = 0 and HOATDONG.IDHD = HOATDONGTHEONGAY.IDHD and NGAYKETTHUCDK < FORMAT(GETDATE(),'yyyy-MM-dd')
and HOATDONGTHEONGAY.TRANGTHAI != 1 and HOATDONGTHEONGAY.TRANGTHAI = 0

update HOATDONGTHEONGAY set TRANGTHAI = 3 where disabled = 0 and NGAYBATDAUDIEMDANH < FORMAT(GETDATE(),'yyyy-MM-dd') and HOATDONGTHEONGAY.TRANGTHAI != 1 and HOATDONGTHEONGAY.TRANGTHAI IN (2,4)

select count(*) from HOATDONGTHEONGAY where IDHD=8 and TRANGTHAI IN (3,1) and disabled = 0

update HOATDONG set TINHTRANG = 2,ngaysua = '0001-01-01',nguoisua = '' where idhd =8

select * from DANGKY



select HOATDONG.TIEUDE,dangky.ngayhuy,dangky.NGAYDANGKY,HOATDONGTHEONGAY.LOAI_BUOI,dangky.TRANGTHAI,HOATDONG.MAHD from dangky  
inner join HOATDONGTHEONGAY ON HOATDONGTHEONGAY.IDBUOI = dangky.IDBUOI 
inner join HOATDONG ON HOATDONG.IDHD = HOATDONGTHEONGAY.IDHD  
where IDSV='3'
   ORDER BY NGAYDANGKY

   update DANGKY set TRANGTHAI = 3,NGAYHUY = GETDATE() 
   from HOATDONGTHEONGAY 
   where IDDK IN (select IDDK
   from HOATDONGTHEONGAY,DANGKY
   where HOATDONGTHEONGAY.IDBUOI = DANGKY.IDBUOI 
   and  HOATDONGTHEONGAY.NGAYBATDAUDIEMDANH < FORMAT(GETDATE(),'yyyy-MM-dd') and IDDK NOT IN( select DANGKY.IDDK from DIEMDANH,DANGKY,HOATDONGTHEONGAY where DIEMDANH.IDBUOI = DANGKY.IDBUOI and DIEMDANH.IDSV = DANGKY.IDSV and HOATDONGTHEONGAY.IDBUOI = DANGKY.IDBUOI 
   and  HOATDONGTHEONGAY.NGAYBATDAUDIEMDANH < FORMAT(GETDATE(),'yyyy-MM-dd'))) 

   SELECT HOATDONG.MAHD,HOATDONG.IDHD,HOATDONG.TIEUDE,HOATDONGTHEONGAY.IDBUOI,HOATDONGTHEONGAY.NGAYBATDAUDIEMDANH FROM HOATDONGTHEONGAY LEFT JOIN DANGKY ON HOATDONGTHEONGAY.IDBUOI = DANGKY.IDBUOI INNER JOIN HOATDONG ON HOATDONGTHEONGAY.IDHD = HOATDONG.IDHD WHERE DANGKY.IDSV = 3 AND HOATDONGTHEONGAY.TRANGTHAI = 4 UNION ALL  SELECT HOATDONG.MAHD,HOATDONG.IDHD,HOATDONG.TIEUDE,HOATDONGTHEONGAY.IDBUOI,HOATDONGTHEONGAY.NGAYBATDAUDIEMDANH FROM HOATDONGTHEONGAY INNER JOIN HOATDONG ON HOATDONGTHEONGAY.IDHD = HOATDONG.IDHD   where NOT exists (SELECT HOATDONG.MAHD,HOATDONG.IDHD,HOATDONG.TIEUDE,HOATDONGTHEONGAY.IDBUOI,HOATDONGTHEONGAY.NGAYBATDAUDIEMDANH FROM HOATDONGTHEONGAY   LEFT JOIN DANGKY ON HOATDONGTHEONGAY.IDBUOI = DANGKY.IDBUOI   INNER JOIN HOATDONG ON HOATDONGTHEONGAY.IDHD = HOATDONG.IDHD   WHERE DANGKY.IDSV = 3 AND HOATDONGTHEONGAY.TRANGTHAI = 4) AND HOATDONGTHEONGAY.TRANGTHAI = 4

   update DANGKY set TRANGTHAI = 3,NGAYHUY = GETDATE() from HOATDONGTHEONGAY 
   where IDDK IN 
   (select IDDK from HOATDONGTHEONGAY,DANGKY where HOATDONGTHEONGAY.IDBUOI = DANGKY.IDBUOI and  HOATDONGTHEONGAY.IDBUOI = ) 
   and IDDK NOT IN( select DANGKY.IDDK from DIEMDANH,DANGKY,HOATDONGTHEONGAY 
   where DIEMDANH.IDBUOI = DANGKY.IDBUOI and DIEMDANH.IDSV = DANGKY.IDSV and HOATDONGTHEONGAY.IDBUOI = DANGKY.IDBUOI and  HOATDONGTHEONGAY.NGAYBATDAUDIEMDANH < FORMAT(GETDATE(),'yyyy-MM-dd'))) 

   SELECT HOATDONG.MAHD,HOATDONG.IDHD,HOATDONG.TIEUDE,HOATDONGTHEONGAY.IDBUOI,HOATDONGTHEONGAY.NGAYBATDAUDIEMDANH    
   FROM HOATDONGTHEONGAY  LEFT JOIN DANGKY ON HOATDONGTHEONGAY.IDBUOI = DANGKY.IDBUOI  
   INNER JOIN HOATDONG ON HOATDONGTHEONGAY.IDHD = HOATDONG.IDHD WHERE DANGKY.IDSV = 3 
    AND HOATDONGTHEONGAY.TRANGTHAI = 3 and DANGKY.TRANGTHAI NOT IN (1,2)
	 and HOATDONGTHEONGAY.IDBUOI not in 
	 ( SELECT HOATDONGTHEONGAY.IDBUOI FROM HOATDONGTHEONGAY    
	 INNER JOIN HOATDONG ON HOATDONGTHEONGAY.IDHD = HOATDONG.IDHD 
	 INNER JOIN PHAN_HOI ON PHAN_HOI.IDBUOI = HOATDONGTHEONGAY.IDBUOI   
	  WHERE PHAN_HOI.IDSV = 3 AND HOATDONGTHEONGAY.TRANGTHAI = 3)
	   UNION ALL	
	   SELECT HOATDONG.MAHD,HOATDONG.IDHD,HOATDONG.TIEUDE,HOATDONGTHEONGAY.IDBUOI,HOATDONGTHEONGAY.NGAYBATDAUDIEMDANH 
	   FROM HOATDONGTHEONGAY INNER JOIN HOATDONG ON HOATDONGTHEONGAY.IDHD = HOATDONG.IDHD   where HOATDONGTHEONGAY.IDBUOI 
	   not in (SELECT HOATDONGTHEONGAY.IDBUOI FROM HOATDONGTHEONGAY    LEFT JOIN DANGKY ON HOATDONGTHEONGAY.IDBUOI = DANGKY.IDBUOI   
	    INNER JOIN HOATDONG ON HOATDONGTHEONGAY.IDHD = HOATDONG.IDHD    WHERE DANGKY.IDSV = 3 AND HOATDONGTHEONGAY.TRANGTHAI = 3 
		and DANGKY.TRANGTHAI NOT IN (1,2))  AND HOATDONGTHEONGAY.TRANGTHAI = 3 and HOATDONGTHEONGAY.IDBUOI 
		NOT IN (SELECT HOATDONGTHEONGAY.IDBUOI FROM HOATDONGTHEONGAY   
		INNER JOIN HOATDONG ON HOATDONGTHEONGAY.IDHD = HOATDONG.IDHD 
		INNER JOIN PHAN_HOI ON PHAN_HOI.IDBUOI = HOATDONGTHEONGAY.IDBUOI   
		WHERE PHAN_HOI.IDSV = 3 AND HOATDONGTHEONGAY.TRANGTHAI = 3 ) and HOATDONGTHEONGAY.IDBUOI  not in (SELECT HOATDONGTHEONGAY.IDBUOI FROM HOATDONGTHEONGAY    LEFT JOIN DIEMDANH ON HOATDONGTHEONGAY.IDBUOI = DIEMDANH.IDBUOI   INNER JOIN HOATDONG ON HOATDONGTHEONGAY.IDHD = HOATDONG.IDHD    WHERE DIEMDANH.IDSV = 3 AND HOATDONGTHEONGAY.TRANGTHAI = 3 )


   Select * from PHAN_HOI
   where TRANGTHAI = 3 and IDBUOI not in (select IDBUOI from DANGKY where IDSV = 3)
   
   select IDBUOI from DIEMDANH where IDSV = 3 

   select ID_PHAN_HOI,MA_PHAN_HOI,PHAN_HOI.TIEUDE,PHAN_HOI.NGAYTAO,HOATDONG.MAHD as MA, HOATDONGTHEONGAY.NGAYBATDAUDIEMDANH AS NGAY, PHAN_HOI.NGUOIDUYET,PHAN_HOI.NGAYDUYET,PHAN_HOI.TRANGTHAI,PHAN_HOI.LOAI_PHAN_HOI,PHAN_HOI.NOIDUNG,GIANG_VIEN.TENGV 
   from PHAN_HOI  
    LEFT JOIN HOATDONGTHEONGAY ON HOATDONGTHEONGAY.IDBUOI = PHAN_HOI.IDBUOI   
	INNER JOIN HOATDONG ON HOATDONGTHEONGAY.IDHD = HOATDONG.IDHD  
	LEFT JOIN GIANG_VIEN ON GIANG_VIEN.ID_GV = PHAN_HOI.NGUOIDUYET   
	where PHAN_HOI.ngaytao >= '2022/11/20' and PHAN_HOI.ngaytao <= '2022/11/20' 
	and PHAN_HOI.IDSV = 3 UNION ALL   
	select ID_PHAN_HOI,MA_PHAN_HOI,PHAN_HOI.TIEUDE,PHAN_HOI.NGAYTAO,VI_PHAM.MA_VI_PHAM as MA, VI_PHAM.NGAYTAO AS NGAY, PHAN_HOI.NGUOIDUYET,PHAN_HOI.NGAYDUYET,PHAN_HOI.TRANGTHAI,PHAN_HOI.LOAI_PHAN_HOI,PHAN_HOI.NOIDUNG,GIANG_VIEN.TENGV  from PHAN_HOI   LEFT JOIN VI_PHAM ON VI_PHAM.ID_VI_PHAM = PHAN_HOI.ID_VI_PHAM  INNER JOIN NOI_QUY ON NOI_QUY.ID_NOI_QUY = VI_PHAM.ID_NOI_QUY   INNER JOIN GIANG_VIEN ON GIANG_VIEN.ID_GV = PHAN_HOI.NGUOIDUYET 
    where PHAN_HOI.ngaytao >= '2022/11/20' and PHAN_HOI.ngaytao <= '2022/11/20' and PHAN_HOI.IDSV = 3 and VI_PHAM.TRANGTHAI = 1


	select HOATDONG.IDHD,HOATDONGTHEONGAY.NGAYBATDAUDIEMDANH,HOATDONG.TIEUDE,HOATDONGTHEONGAY.TRANGTHAI,KHOA.TEN_KHOA,HOC_KI.TEN_HK from HOATDONG INNER JOIN HOATDONGTHEONGAY ON HOATDONGTHEONGAY.IDHD = HOATDONGTHEONGAY.IDHD LEFT JOIN KHOA ON KHOA.ID_KHOA = HOATDONG.ID_KHOA LEFT JOIN HOC_KI ON HOC_KI.ID_HK = HOATDONG.ID_HK 

select VI_PHAM.*,MASV,TENSV,NOI_QUY.TEN_NOI_QUY,NOI_QUY.DIEM from VI_PHAM inner join SINHVIEN on SINHVIEN.ID_SV = VI_PHAM.IDSV inner join NOI_QUY on NOI_QUY.ID_NOI_QUY = VI_PHAM.ID_NOI_QUY

SELECT HOATDONG.MAHD,HOATDONG.IDHD,HOATDONG.TIEUDE,HOATDONGTHEONGAY.IDBUOI,HOATDONGTHEONGAY.NGAYBATDAUDIEMDANH FROM HOATDONGTHEONGAY  LEFT JOIN DANGKY ON HOATDONGTHEONGAY.IDBUOI = DANGKY.IDBUOI  INNER JOIN HOATDONG ON HOATDONGTHEONGAY.IDHD = HOATDONG.IDHD WHERE DANGKY.IDSV = " + IDSV + "  AND HOATDONGTHEONGAY.TRANGTHAI = 3 and DANGKY.TRANGTHAI NOT IN (1,2) and HOATDONG.ID_HK = "+idhk+"  and HOATDONGTHEONGAY.IDBUOI  not in ( SELECT HOATDONGTHEONGAY.IDBUOI FROM HOATDONGTHEONGAY    INNER JOIN HOATDONG ON HOATDONGTHEONGAY.IDHD = HOATDONG.IDHD INNER JOIN PHAN_HOI ON PHAN_HOI.IDBUOI = HOATDONGTHEONGAY.IDBUOI   WHERE PHAN_HOI.IDSV = " + IDSV + " AND HOATDONGTHEONGAY.TRANGTHAI = 3  and HOATDONG.ID_HK = "+idhk+") UNION ALL	 SELECT HOATDONG.MAHD,HOATDONG.IDHD,HOATDONG.TIEUDE,HOATDONGTHEONGAY.IDBUOI,HOATDONGTHEONGAY.NGAYBATDAUDIEMDANH  FROM HOATDONGTHEONGAY INNER JOIN HOATDONG ON HOATDONGTHEONGAY.IDHD = HOATDONG.IDHD    where HOATDONGTHEONGAY.IDBUOI not in (SELECT HOATDONGTHEONGAY.IDBUOI FROM HOATDONGTHEONGAY     LEFT JOIN DANGKY ON HOATDONGTHEONGAY.IDBUOI = DANGKY.IDBUOI    INNER JOIN HOATDONG ON HOATDONGTHEONGAY.IDHD = HOATDONG.IDHD     WHERE DANGKY.IDSV = " + IDSV + " AND HOATDONGTHEONGAY.TRANGTHAI = 3 and DANGKY.TRANGTHAI NOT IN (1,2)  and HOATDONG.ID_HK = "+idhk+")   AND HOATDONGTHEONGAY.TRANGTHAI = 3  and HOATDONG.ID_HK = "+idhk+" and HOATDONGTHEONGAY.IDBUOI NOT IN (SELECT HOATDONGTHEONGAY.IDBUOI FROM HOATDONGTHEONGAY INNER JOIN HOATDONG ON HOATDONGTHEONGAY.IDHD = HOATDONG.IDHD  INNER JOIN PHAN_HOI ON PHAN_HOI.IDBUOI = HOATDONGTHEONGAY.IDBUOI   WHERE PHAN_HOI.IDSV = " + IDSV + " AND HOATDONGTHEONGAY.TRANGTHAI = 3   and HOATDONG.ID_HK = "+idhk+")  and HOATDONGTHEONGAY.IDBUOI  not in (SELECT HOATDONGTHEONGAY.IDBUOI FROM HOATDONGTHEONGAY     LEFT JOIN DIEMDANH ON HOATDONGTHEONGAY.IDBUOI = DIEMDANH.IDBUOI   INNER JOIN HOATDONG ON HOATDONGTHEONGAY.IDHD = HOATDONG.IDHD    WHERE DIEMDANH.IDSV = " + IDSV + " AND HOATDONGTHEONGAY.TRANGTHAI = 3  and HOATDONG.ID_HK = "+idhk+")

--select VI_PHAM.ID_VI_PHAM,VI_PHAM.MA_VI_PHAM,TEN_NOI_QUY from VI_PHAM inner join NOI_QUY on NOI_QUY.ID_NOI_QUY = VI_PHAM.ID_NOI_QUY where IDSV = "+idsv+" and VI_PHAM.IDHK = "+idhk+" and VI_PHAM.TRANGTHAI = 1 and IDSV not in (select PHAN_HOI.IDSV from PHAN_HOI inner join VI_PHAM on VI_PHAM.ID_VI_PHAM = PHAN_HOI.ID_VI_PHAM where IDSV = "+idsv+")

select HOATDONG.MAHD,HOATDONG.TIEUDE,HOATDONGTHEONGAY.LOAI_BUOI,HOATDONGTHEONGAY.NGAYBATDAUDIEMDANH 
from HOATDONG INNER JOIN HOATDONGTHEONGAY ON HOATDONG.IDHD = HOATDONGTHEONGAY.IDHD
 where ID_HK = 1 
 order by HOATDONGTHEONGAY.NGAYBATDAUDIEMDANH desc

INSERT INTO KETQUA(IDSV,IDHK,DIEM,LOAI) select ID_SV,1,75,'B' from SINHVIEN where ID_SV NOT IN (select IDSV from KETQUA)

select HOATDONG.IDHD,HOATDONGTHEONGAY.NGAYBATDAUDIEMDANH,HOATDONG.TIEUDE,HOATDONGTHEONGAY.TRANGTHAI,hoatdong.mahd,HOATDONGTHEONGAY.IDBUOI 
from HOATDONG 
INNER JOIN HOATDONGTHEONGAY ON HOATDONGTHEONGAY.IDHD = HOATDONG.IDHD 
where NGAYBATDAUDIEMDANH >= '2022/11/01' and NGAYBATDAUDIEMDANH <= '2022/11/26' and HOATDONGTHEONGAY.TRANGTHAI = 6 and IDBUOI IN (select IDBUOI from HOATDONGTHEONGAY where TRANGTHAI = 6)


select * from KETQUA

select count(*) from PHAN_HOI where ID_VI_PHAM= 1 and TRANGTHAI =1 and idhk=1

select VI_PHAM.ID_VI_PHAM,VI_PHAM.MA_VI_PHAM,TEN_NOI_QUY 
from VI_PHAM inner join NOI_QUY on NOI_QUY.ID_NOI_QUY = VI_PHAM.ID_NOI_QUY 
where IDSV = 3 and VI_PHAM.IDHK = 1 and VI_PHAM.TRANGTHAI = 1 and 
ID_VI_PHAM not in (select PHAN_HOI.ID_VI_PHAM from PHAN_HOI inner join VI_PHAM on VI_PHAM.ID_VI_PHAM = PHAN_HOI.ID_VI_PHAM where PHAN_HOI.IDSV = 3)

update KETQUA set DIEM = 75
select * from KETQUA
update KETQUA set DIEM += HOATDONG.DIEMRL
from DIEMDANH,HOATDONGTHEONGAY,HOATDONG
where KETQUA.IDSV = DIEMDANH.IDSV and HOATDONGTHEONGAY.IDHD = HOATDONG.IDHD and DIEMDANH.IDBUOI = HOATDONGTHEONGAY.IDBUOI and HOATDONG.ID_HK = 1 and HOATDONGTHEONGAY.TRANGTHAI = 6


update KETQUA set DIEM += HOATDONG.DIEMRL 
from PHAN_HOI,HOATDONGTHEONGAY,HOATDONG 
where KETQUA.IDSV = PHAN_HOI.IDSV and HOATDONGTHEONGAY.IDHD = HOATDONG.IDHD and PHAN_HOI.IDBUOI = HOATDONGTHEONGAY.IDBUOI and PHAN_HOI.IDHK = 1 and PHAN_HOI.TRANGTHAI = 1 and HOATDONGTHEONGAY.TRANGTHAI = 6

update KETQUA set DIEM -= HOATDONG.DIEMRL 
from DANGKY,HOATDONGTHEONGAY,HOATDONG
 where KETQUA.IDSV = DANGKY.IDSV and HOATDONGTHEONGAY.IDHD = HOATDONG.IDHD and DANGKY.IDBUOI = HOATDONGTHEONGAY.IDBUOI and HOATDONG.ID_HK = 1 and HOATDONGTHEONGAY.TRANGTHAI = 6 and DANGKY.TRANGTHAI = 3

update KETQUA set DIEM += NOI_QUY.DIEM 
from PHAN_HOI,VI_PHAM,NOI_QUY 
where KETQUA.IDSV = PHAN_HOI.IDSV and PHAN_HOI.ID_VI_PHAM = VI_PHAM.ID_VI_PHAM and NOI_QUY.ID_NOI_QUY = VI_PHAM.ID_NOI_QUY and PHAN_HOI.IDHK = 1 and PHAN_HOI.TRANGTHAI = 1

update KETQUA set DIEM -= NOI_QUY.DIEM 
from VI_PHAM,NOI_QUY 
where KETQUA.IDSV = VI_PHAM.IDSV  and NOI_QUY.ID_NOI_QUY = VI_PHAM.ID_NOI_QUY and VI_PHAM.IDHK = 1 and VI_PHAM.TRANGTHAI = 1

update HOC_KI set TRANGTHAI = 0 where ID_HK = 1

select * from VI_PHAM

select * from KETQUA

select HOATDONG.MAHD,HOATDONG.TIEUDE,HOATDONGTHEONGAY.NGAYBATDAUDIEMDANH,HOATDONGTHEONGAY.LOAI_BUOI,DANGKY.GHICHU,0 as 'hinh_thuc',HOATDONG.DIEMRL 
from DANGKY 
inner join HOATDONGTHEONGAY on HOATDONGTHEONGAY.IDBUOI = DANGKY.IDBUOI 
inner join HOATDONG on HOATDONG.IDHD = HOATDONGTHEONGAY.IDHD 
where DANGKY.TRANGTHAI = 3 and IDSV = 3 and HOATDONG.ID_HK = 1 
union all 
select HOATDONG.MAHD,HOATDONG.TIEUDE,HOATDONGTHEONGAY.NGAYBATDAUDIEMDANH,HOATDONGTHEONGAY.LOAI_BUOI,DIEMDANH.GHICHU,1 as 'hinh_thuc',HOATDONG.DIEMRL 
from DIEMDANH 
inner join HOATDONGTHEONGAY on HOATDONGTHEONGAY.IDBUOI = DIEMDANH.IDBUOI 
inner join HOATDONG on HOATDONG.IDHD = HOATDONGTHEONGAY.IDHD where IDSV = 3 and HOATDONG.ID_HK = 1
union all select HOATDONG.MAHD,HOATDONG.TIEUDE,HOATDONGTHEONGAY.NGAYBATDAUDIEMDANH,HOATDONGTHEONGAY.LOAI_BUOI,PHAN_HOI.NOIDUNG as 'GHICHU',2 as 'hinh_thuc',HOATDONG.DIEMRL from PHAN_HOI inner join HOATDONGTHEONGAY on HOATDONGTHEONGAY.IDBUOI = PHAN_HOI.IDBUOI inner join HOATDONG on HOATDONG.IDHD = HOATDONGTHEONGAY.IDHD where IDSV = 3 and HOATDONG.ID_HK = 1 and PHAN_HOI.TRANGTHAI = 1

select HOATDONG.MAHD,HOATDONG.TIEUDE,HOATDONGTHEONGAY.NGAYBATDAUDIEMDANH,HOATDONGTHEONGAY.LOAI_BUOI,DANGKY.GHICHU,N'Không tham gia' as 'hinh_thuc',HOATDONG.DIEMRL
 from DANGKY 
 inner join HOATDONGTHEONGAY on HOATDONGTHEONGAY.IDBUOI = DANGKY.IDBUOI 
 inner join HOATDONG on HOATDONG.IDHD = HOATDONGTHEONGAY.IDHD
  where DANGKY.TRANGTHAI = 3 and IDSV = 1 and HOATDONG.ID_HK = 1 and HOATDONGTHEONGAY.TRANGTHAI = 6
  union all 
  select HOATDONG.MAHD,HOATDONG.TIEUDE,HOATDONGTHEONGAY.NGAYBATDAUDIEMDANH,HOATDONGTHEONGAY.LOAI_BUOI,DIEMDANH.GHICHU,N'Tham gia' as 'hinh_thuc',HOATDONG.DIEMRL 
  from DIEMDANH 
  inner join HOATDONGTHEONGAY on HOATDONGTHEONGAY.IDBUOI = DIEMDANH.IDBUOI 
  inner join HOATDONG on HOATDONG.IDHD = HOATDONGTHEONGAY.IDHD 
  where IDSV = 1 and HOATDONG.ID_HK = 1 and HOATDONGTHEONGAY.TRANGTHAI = 6
  union all 
  select HOATDONG.MAHD,HOATDONG.TIEUDE,HOATDONGTHEONGAY.NGAYBATDAUDIEMDANH,HOATDONGTHEONGAY.LOAI_BUOI,PHAN_HOI.NOIDUNG as 'GHICHU',N'Phản hồi' as 'hinh_thuc',HOATDONG.DIEMRL 
  from PHAN_HOI 
  inner join HOATDONGTHEONGAY on HOATDONGTHEONGAY.IDBUOI = PHAN_HOI.IDBUOI 
  inner join HOATDONG on HOATDONG.IDHD = HOATDONGTHEONGAY.IDHD 
  where IDSV = 3 and HOATDONG.ID_HK = 1 and PHAN_HOI.TRANGTHAI = 1

  select VI_PHAM.MA_VI_PHAM,NOI_QUY.TEN_NOI_QUY,VI_PHAM.NGAYTAO,VI_PHAM.NOIDUNG,'Vi phạm nội quy' as 'hinh_thuc',NOI_QUY.DIEM from VI_PHAM INNER JOIN NOI_QUY on NOI_QUY.ID_NOI_QUY = VI_PHAM.ID_NOI_QUY where IDSV = 3 and VI_PHAM.IDHK = 1 and VI_PHAM.TRANGTHAI = 1 UNION ALL select VI_PHAM.MA_VI_PHAM,NOI_QUY.TEN_NOI_QUY,VI_PHAM.NGAYTAO,PHAN_HOI.NOIDUNG,'Phản hồi vi phạm nội quy' as 'hinh_thuc' from VI_PHAM  INNER JOIN NOI_QUY on NOI_QUY.ID_NOI_QUY = VI_PHAM.ID_NOI_QUY INNER JOIN PHAN_HOI on PHAN_HOI.ID_VI_PHAM = VI_PHAM.ID_VI_PHAM where PHAN_HOI.IDSV = 3 and VI_PHAM.IDHK = 1 and VI_PHAM.TRANGTHAI = 1 

select count(*) from HOATDONG INNER JOIN HOATDONGTHEONGAY ON HOATDONGTHEONGAY.IDHD = HOATDONG.IDHD where HOATDONGTHEONGAY.trangthai NOT IN (6,7) and HOATDONG.ID_HK = 1

select * from PHAN_HOI

select * from HOATDONG INNER JOIN HOATDONGTHEONGAY ON HOATDONGTHEONGAY.IDHD = HOATDONG.IDHD where HOATDONGTHEONGAY.trangthai NOT IN (6,7) and HOATDONG.ID_HK = 2 and HOATDONGTHEONGAY.disabled

select * from KETQUA